### ISSUE TITLE
Docker files for server and client not found

### ISSUE THREAD

**Issue by ayham-hassan** [nirgn975/Angular-Sanic-Seed-Project#95]
```
[x ] Bug report
[ ] Feature request
[ ] Clarification on the documentation
```

**Current behavior**
Docker build images for server and client not working

**What is the expected behavior?** (if you know how it should behave)
Docker configuration files should exist in server and client folders as mentioned in documentaion

**Comment by ziaulain** [comment]
having same issue..

**Comment by nirgn975** [comment]
Still a work in progress, we moving from docker compose to kubernetes, will be updated in the coming week or two.

**Comment by ayham-hassan** [comment]
Lool!

we are working too on that. if you want we can help also :)

**Comment by nirgn975** [comment]
Done (:
