### ISSUE TITLE
Move to kubernetes

### ISSUE THREAD

**Issue by nirgn975** [nirgn975/Angular-Sanic-Seed-Project#97]
- [ ] Create Dockerfile for server.
- [ ] Create `yaml` file for client.
- [ ] Create `yaml` file for server.
- [ ] Create `yaml` file for db (postgres).
- [ ] Update `README.md` and add a `deploy` commands to README for GCP.

**Comment by gowthamraj198** [comment]
Hello - I would like to take this up! But README says there is already docker in place for client and server.

**Comment by nirgn975** [comment]
@gowthamraj198 Great! 
I updated the `client` and `server` apps, so there is no `dockerfile`s in place, you'll need to create them in this PR.
As you can see one of the tasks here is to update the `README.md` file at the end of the change.

**Comment by gowthamraj198** [comment]
But this is assigned to your name.. Shall I also join?

**Comment by nirgn975** [comment]
Yeah, I'll add you to the PR, and I'll open a new branch for it and let's work together on this.

I thought we'll start with GCP and then move to test this in AWS and Azure. 
- The client app (angular) should have a `yaml` file that deploy the app to GCP Storage.
- The server app (sanic) should have a `yaml` file to deploy itself to the kubernetes cluster.
- There should be a `yaml` file (or set of commands in the `README.md`) to deploy a postgres db to the  kubernetes cluster.

**Comment by gowthamraj198** [comment]
I will send the PR with a new branch now

**Comment by nirgn975** [comment]
@gowthamraj198 
Saw the PR, great start. Are you gonna write the `dockerfile`s?
Also, as I said, the `client` app doesn't need a `dockerfile`. We need a `cloudbuild.yaml` file for GCP platform, that will build the angular app (`npm run build`) and then upload the build files to GCP storage.

**Comment by gowthamraj198** [comment]
Yes. I will start with dockerfiles. As I am new to kubernetes it will take some time to complete the tasks. But I can make significant progress every week.

**Comment by nirgn975** [comment]
Great! Do the `dockerfile`s and I'll help with the kubernetes yaml files.

**Comment by gowthamraj198** [comment]
'pipenv shell . ' command not working.

just staying here 
` Loading .env environment variables…
Launching subshell in virtual environment…
 . /Users/gowthamr/.local/share/virtualenvs/Angular-Sanic-Seed-Project-Xcm2smXN/bin/activate                                                                                                            
.
0%  . /Users/gowthamr/.local/share/virtualenvs/Angular-Sanic-Seed-Project-Xcm2smXN/bin/activate
(Angular-Sanic-Seed-Project) 0% .
.: not enough arguments
(Angular-Sanic-Seed-Project) 0%  `

Not sure how to make server up..

**Comment by nirgn975** [comment]
`pipenv shell` inside the `server` directory should work.
To get the server going (after `pipenv shell` and `pipenv install` if it didn't do that automatically) do `python main.py` (should be python 3.4 and up).

Read the `README.md` file in the `server` directory, you should create a `.env` file with all the environment variables in the `README.md` file.
